### ISSUE TITLE
Offset and limit issue in Fusion Search API

### ISSUE THREAD

**Issue by pkuong** [Yelp/yelp-fusion#307] opened 2017-10-04 21:15 UTC
## Overview
- **Client ID:** cdGCO1WE0esxOqSzKXiKHQ
- **Issue type:** bug
- **Summary:** response from Search API seems return random businesses when navigating through different offset
- **Platform:** MACOSX

## Description
Response from Search API seems return random businesses when navigating. I'm trying to get all business for a location. There are more than 50 businesses. So, I was thinking different offset will give me the next 50, and so on.....but when I go to next offset, I see same businesses with the same yelp id.

Also, I noticed that there is response for wrong offset. For example, there are total 1234 business indicated by the response. However, somehow when I have offset 50 and limit 50, I still get response. Shouldn't offset 50 and limit 50 gives me record 2500 to 2550? I should get empty response no?

### Endpoint
Fusion Search API

**Comment by mittonk** [comment] 2017-10-09 13:24
@pkuong : `limit` and `offset` work like they do in MySQL, PostgreSQL, and many other databases. (`offset` counts by businesses, not by windows-of-size-`limit`.)

Let's try a simpler example.

For your 1234 possible restaurants:
`offset=0`, `limit=3` will give numbers 1, 2, 3.
`offset=10`, `limit=3` will give numbers 11, 12, 13.
`offset=20`, `limit=3` will give numbers 21, 22, 23.

So, `offset=50`, `limit=50` will give numbers 51 -- 100.

If you want the first 100 businesses, you'll need two calls:
`offset=0`, `limit=50` : businesses 1 -- 50.
`offset=50`, `limit=50`: businesses 51 -- 100.

Does that get you going in the right direction?

**Comment by pkuong** [comment] 2017-10-09 13:43
I understand how this works. I'm saying it does not work as what it supposes to. As I mentioned above, when I advancing offset, I see results with the same unique yelp business id ...and when I reach what it supposes to be the last page, i can keep advance the offset.

**Comment by mittonk** [comment] 2017-10-10 13:06
@pkuong : Thanks for the example URLs, that helps.

This definitely looks like a bug in the `total` calculation --- same issue as #264.

As a workaround: your example queries seem to give good actual businesses (just confusing `total` values):
/v3/businesses/search?location=metlife+building&radius=10
> I got 7 businesses
Me too, good:
```
[
	"bunda-jewelry-appraisers-new-york",
	"itseasy-passport-and-visa-services-new-york",
	"naples-45-ristorante-e-pizzeria-new-york",
	"cucina-and-company-new-york",
	"metlife-building-new-york",
	"law-offices-of-michael-j-simon-new-york",
	"cb-richard-ellis-new-york-7"
]
```

/v3/businesses/search?location=metlife+building&limit=5&offset=1&radius=10
> I got 5 businesses
I see `total: 5` (wrong), but I do see 6 actual businesses listed as expected:
```
[
	"itseasy-passport-and-visa-services-new-york",
	"naples-45-ristorante-e-pizzeria-new-york",
	"cucina-and-company-new-york",
	"metlife-building-new-york",
	"law-offices-of-michael-j-simon-new-york",
	"cb-richard-ellis-new-york-7"
]
```
(We've `offset` past `bunda-jewelry-appraisers-new-york`.)

So, linking this to #264 while we debug the `total` value.

**Comment by watterso** [comment] 2017-11-30 01:17
Closing as a dupe of #264.

**Closed by watterso** 2017-11-30 01:17 UTC
Labels: bug, tracked-internally
