### ISSUE TITLE
Does Yelp really want you to be able to use their API?

### ISSUE THREAD

**Issue by AnnaDanielle** [Yelp/yelp-fusion#197] opened 2017-03-20 23:08 UTC
I've been trying for months to return accurate results with my term+location searches. I'm noticing that my results are changing every single time I'm searching and they aren't even returning accurate results. What is going on? Does Yelp intend for developers to drive themselves crazy trying to figure out Yelp's "best match" search? Even when I search by distance, or limit radius, it's not responding in the way expected.

Can someone provide some insight as to how results are returned, and why results change when you search multiple times? I'd love to understand just how Yelp determines something is a "best match", especially when I may be searching closed establishments.

**Comment by tomelm** [comment] 2017-03-21 00:29
On our side, search gets re-indexed periodically and search results could change for any number of reasons after that (business closed, moved, new businesses, ranking, etc). @AnnaDanielle could you give examples of this happening to you (requests and responses)? I'd like to make sure nothing's broken.

When you're saying you're searching for closed establishments do you mean permanently closed? What are you trying to build? I'm curious to learn more.

As far as how best match works, it's hard to dive into specifics. It's taking into account a lot of variables to determine the most relevant results to return (rating, keyword matches, categories, business names, reviews, etc) so different results could show up based on what got re-indexed.

**Comment by AnnaDanielle** [comment] 2017-03-21 00:58
I'm seeing this inconsistency on a consistent basis, so I am thinking this randomness is built into your API.

I've been trying to track restaurant 'life' in LA over the past 3+ years. I'm feeding Yelp facility inspection names (term) and facility location (address) over the past 3 years, and trying to gather some Yelp parameters to build a model to understand and predict restaurant closings.

Inherently, some of these businesses will be permanently closed, and share addresses with other restaurants. That's ok, because I'm searching each name with the same address, so in theory, I should see multiple yelp business ids that share an address. 

But I'm not even able to really get to the root of that problem! I've been first doing a phone search when possible (50% of my data has a phone), and I get about 20% accurate matches (whew, that's REALLY low). Then I feed those failures through a term/location search, and at the end of it, I'm left with only 30% accurate searches OVERALL. So the data I'm working with is completely biased by Yelp's inability to return what I'm actually searching for. 

When I go into google, and just simply type in the term and location + yelp, that will be my first result--the one I'm really looking for.

**Comment by tomelm** [comment] 2017-03-21 17:13
We definitely do not have randomness built in, I can assure you that. I don't know how accurate phone search will be, businesses on Yelp have the ability to use an intermediary service for phone numbers which could impact search.

Can you share examples? I'd really like to look into this but I can't reproduce this on my side and I haven't experienced this before.

**Comment by AnnaDanielle** [comment] 2017-03-21 20:38
Sure, I'm doing this across 9000+ restaurants, but here's one.

I'm searching the first two columns through term and location:
![image](https://cloud.githubusercontent.com/assets/24233531/24169610/665356e0-0e3b-11e7-9f59-796514569199.png)

The response to the "best match" makes no sense. How is this determined? 

Here's what happen when I type it into google, trying to figure out why Yelp can't search my requests--it's the first response that I want!

![image](https://cloud.githubusercontent.com/assets/24233531/24169706/b43eda3c-0e3b-11e7-93f4-d865188c449e.png)

**Comment by tomelm** [comment] 2017-03-21 21:47
Thanks! There's two things going on right now:
1. It doesn't show up on yelp.com either: https://www.yelp.com/search?find_desc=161+street+pizzeria&find_loc=3252+Cahuenga+Blvd+W%2C+Los+Angeles%2C+CA&ns=1
2. The API is returning different results than yelp.com

I'll talk to the search team and see what's happening but I can't really give you any sort of ETA right now.

**Comment by mittonk** [comment] 2017-03-21 22:04
Hm, looks like "161" and "161st" are getting parsed as different.

* https://www.yelp.com/search?find_desc=161st+street+pizzeria&find_loc=3252+Cahuenga+Blvd+W,+Los+Angeles,+CA shows our desired match (https://www.yelp.com/biz/161st-street-pizzeria-los-angeles-3).
* https://api.yelp.com/v3/businesses/search?term=161ST+PIZZA&location=3252+CAHUENGA+BLVD+W+LOS+ANGELES+90068
```
{
  "businesses": [
    {
      "id": "161st-street-pizzeria-los-angeles-3",
      "rating": 4,
      "url": "https://www.yelp.com/biz/161st-street-pizzeria-los-angeles-3?adjust_creative=ssWONR4BhYiARowH3vsVEA&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=ssWONR4BhYiARowH3vsVEA",
...
```

I'd expect the stemming to do better than that.

**Comment by tomelm** [comment] 2017-03-21 22:05
@AnnaDanielle so searching for "161_st_ Street Pizzeria" does in fact return the correct data on the API: 

```
{
	"businesses": [
		{
			"name": "161st Street Pizzeria",
			"image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/RyWR7awTBVmVuST9Z2K5_Q/o.jpg",
			"location": {
				"zip_code": "90068",
				"address3": null,
				"country": "US",
				"address2": "",
				"state": "CA",
				"address1": "3252 Cahuenga Blvd W",
				"city": "Los Angeles",
				"display_address": [
					"3252 Cahuenga Blvd W",
					"Los Angeles, CA 90068"
				]
			},
			"id": "161st-street-pizzeria-los-angeles-3",
			"coordinates": {
				"longitude": -118.3491067,
				"latitude": 34.1299201
			},
			"distance": 3.076505593578,
			"phone": "+13238516161",
			"rating": 4.0,
			"review_count": 4,
...
			],
			"url": "https://www.yelp.com/biz/161st-street-pizzeria-los-angeles-3?adjust_creative=lrVVpyP-aBRmP1I1KUqXkw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=lrVVpyP-aBRmP1I1KUqXkw",
...
}
```

It looks like we're not handling the difference in naming correctly. Still talking to the search team but I'm not sure if we'll have a better answer soon.

**Comment by AnnaDanielle** [comment] 2017-03-21 22:10
Do you know what other stemming issues are out there? I've found that pound signs throw off the best results significantly, and sometimes even forgetting a space will return something completely different. I have a ton of issues (probably focused/masked around stemming), but I'm trying to solve them systematically instead of one-by-one. Is the term search really just going through the business ids? That's when I appear to get the best matches. It's almost like I'd want to guess at the business ID in order to return an accurate result.

**Comment by tomelm** [comment] 2017-03-22 17:44
That's kind of a big question that I can't really answer. The search term is not only going through business names, it's also going through reviews, categories, and a lot of other data.

**Comment by tomelm** [comment] 2017-03-27 20:33
I pushed a change out that improves search relevancy but I don't think there are any changes we can make towards stemming at the moment. We're working to release some functionality that'll be a better match for this use case in the future but I don't have a specific timeline to share yet.

Outside of those couple of stemming issues, do you have examples of other bad queries you were seeing?

**Comment by AnnaDanielle** [comment] 2017-03-27 23:02
Sure, here's another one:
term: 'Subway',
location: '2601 S LA BREA AVE LOS ANGELES 90016'

It returns a bunch of subways, but none at the right address.

I can just keep posting issues as I see them...

**Comment by AnnaDanielle** [comment] 2017-03-27 23:09
another:
term: 'NAM KOONG CLUB', 
location: '3514 W 8TH ST LOS ANGELES 90005'

It's rather odd that the word 'club' is not allowing yelp to come up with accurate matches.

**Comment by drosophila** [comment] 2017-06-22 03:44
Hi @AnnaDanielle , I'm having the same issue. I have a roster of restaurant names and addresses. I am not confident about the accuracy of the names or whether or not the restaurant is permanently closed or open. I am trying to extract the restaurant names and ratings based on the addresses. 
Even when an address search returns the correct business (among a list of businesses) on yelp.com the API  result is a hit and miss, and mostly a miss. 
However I might have found a way to tip the scale by adding a radius constraint:

```
def search(bearer_token, term, location):
    """Query the Search API by a search term and location.
    Args:
        term (str): The search term passed to the API.
        location (str): The search location passed to the API.
    Returns:
        dict: The JSON response from the request.
    """

    url_params = {
        'term': term.replace(' ', '+'),
        'location': location.replace(' ', '+'),
        'limit': SEARCH_LIMIT,
        'radius': 50
    }
    return request(API_HOST, SEARCH_PATH, bearer_token, url_params=url_params)
```
By adding a radius constraint to ```def search()```  I managed to get better results. However for restaurant that are permanently closed on Yelp (i can only find these through a google search) this still does not work at all. You'll get the name of some other unrelated business.

If you make the radius too small chances are you will miss your target.

**Comment by tomelm** [comment] 2017-07-13 17:48
We released some endpoints into beta that'll help you match specific businesses against Yelp businesses: https://www.yelp.com/developers/documentation/v3/business_match

This will work way better than search for finding exact matches. It's still in beta though so we're working out some bugs, if there's any feedback please create new issues! Closing this one.

**Closed by tomelm** 2017-07-13 17:48 UTC
Labels: bug, tracked-internally

**Comment by dnbwise** [comment] 2017-09-12 19:42
I'm seeing the same issues looking for doctors using the search api. Here is a simple example: 

google (first result): https://www.google.com/search?q=david+logan+pittsburgh+pa+inurl%3Ayelp

yelp site search (2 relevant results): https://www.yelp.com/search?find_desc=logan+david&find_loc=Pittsburgh%2C+PA

yelp fusion (no result): https://api.yelp.com/v3/businesses/search?term=logan, david&location=Pittsburgh, PA&radius=40000&categories=physicians

**Comment by mittonk** [comment] 2017-09-13 18:53
@dnbwise : You're seeing a different (and simpler) issue --- neither of those businesses have reviews, so are not returned by the Fusion API.
* https://www.yelp.com/developers/documentation/v3/business_search
> Note: at this time, the API does not return businesses without any reviews.

**Comment by AmitMirgal** [comment] 2018-04-07 18:02
@mittonk so, how can I get that business information which does not have a review?

**Comment by watterso** [comment] 2018-04-09 18:46
@AmitMirgal as mittonk mentioned neither the [business search](https://www.yelp.com/developers/documentation/v3/business_search) nor the [business lookup](https://www.yelp.com/developers/documentation/v3/business) will return information for businesses with no reviews. Getting information for a business without any reviews is just not a use case supported by the API.

**Comment by DawnMKing** [comment] 2018-05-08 16:00
I am having a similar issue. I ran a query yesterday that collected results on 435 doctors office location. If I rerun the same exact query, none of those offices are showing up today.

**Comment by AmitMirgal** [comment] 2018-05-09 03:05
@DawnMKing It depends on the scenario like if the store is closed it won't give you the result... so I assume that the store might be closed...

**Comment by DawnMKing** [comment] 2018-05-31 17:32
@AmitMirgal That is not the problem... if the store is closed, but there is a review, there is a tag given in the response saying that it is closed. This is not happening for just one query either... The other day I was running a location search based off of location name and address, everything was working fine for the first 3,400 queries, then yelp stopped producing results at reported the last ~1,600 queries that no business exited. This exhausted my 5,000 a day limit. When I later reran the 1,600, I got results. It seems that Yelp is hit or miss on when it the API actually makes legit calls because this example above is not the first time this has happened. Is there any insight as to why, or how to fix it?
