### ISSUE TITLE
feature request: a way to search for closed businesses

### ISSUE THREAD

**Issue by sulphide0** [Yelp/yelp-fusion#325] opened 2017-11-15 22:16 UTC
would it be possible for the yelp apis to provide a way to search for closed businesses? we're trying to develop a mechanism to identify outdated references to businesses in our content and we have a very large corpus. rather than send hundreds of thousands of requests to yelp to check if a business is closed we feel it would be more efficient to start with a list of closed businesses for a given city and then  search our content for only the closed businesses (which would be a very small subset of all business references in our content)

**Comment by mittonk** [comment] 2017-11-28 19:27
Interesting idea --- we've had a few questions about this.  No plans yet.

**Comment by watterso** [comment] 2017-11-30 00:51
Closing as duplicate of #249 .

**Closed by watterso** 2017-11-30 00:51 UTC
Labels: enhancement
