### ISSUE TITLE
Getting reviews for a business with less than 3 reviews yields an HTTP 403 "Access Forbidden" error

### ISSUE THREAD

**Issue by vineus** [Yelp/yelp-fusion#136] opened 2016-12-08 17:21 UTC
You can try by trying to retrieve reviews from the following yelp Ids:

`istr-paris`
`comptoir-des-recettes-paris`

Expected output: the 1 or 2 reviews available.

This bug is not present in API v2 (the reviews are in the `reviews` array of a `business` call response)

**Comment by mittonk** [comment] 2016-12-08 18:57
@vineus : Looks like the reviews are in French.  Are you supplying `locale=fr_FR`?

**Comment by mittonk** [comment] 2016-12-08 18:58
(Looks like our "unreviewed" check is specific to the locale requested, which defaults to `locale=en_US` if not supplied.)

**Comment by vineus** [comment] 2016-12-09 09:12
Ok so... is it a bug ? Or is it the expected behavior ? Should I try every possible locales (kidding. No.) ? Right now my solution is to fallback to v2 when I have a 403 which is not ideal :-)

**Comment by mittonk** [comment] 2016-12-09 17:36
I usually let the user choose the locale --- a Spanish speaker would want to see Spanish reviews.

Yelp's web site does this based on the language-picker in the lower-right corner; Yelp's mobile apps use the device interface language.

It's expected behavior.  #66 asks for `locale=*`, sounds like that's what you're reaching for as well.

v2 does have `lang_filter=false` as the default, so this is indeed a reduction in functionality.

This ticket's the clearer of the two --- marking it as the main open issue, and looking into it a little.

**Comment by vineus** [comment] 2016-12-09 17:46
OK, thank you for the very clear explanation!

**Comment by mittonk** [comment] 2017-01-11 19:45
@vineus : I'm looking into this, I'd like a little more info about your use case.

If you have a user who reads French, and a business has 0 reviews and 2 Japanese ones, would your system show them the Japanese reviews?

**Comment by vineus** [comment] 2017-01-12 09:33
Hey @mittonk 

The use case is about the business owner. I'm building a system where the business owner can quickly look up his latest reviews. The owner does not really care if the reviews are in Japanese or French or any other language (and she can translate them if needed) but deeply cares about if people are reviewing his review and what they are saying about it.

**Comment by mittonk** [comment] 2017-01-13 20:03
@vineus : Good use case, but I wonder if it might be a better match for
* https://www.yelp.com/knowledge

In particular, the Fusion API Reviews endpoint doesn't necessarily provide the 3 newest reviews:
* https://www.yelp.com/developers/documentation/v3/business_reviews

**Comment by vineus** [comment] 2017-01-14 17:55
OK, so the solution is to fallback to V2 then. Thanks for the clarification!

in the meantime, will checkout knowledge, I didn't knew about it!

Could you at the very least send back an empty response (with a 200 OK) and not a "access forbidden" error code?

**Comment by mittonk** [comment] 2017-07-06 13:53
@vineus : For the reviewed-but-not-in-this-language businesses, we're now at least giving a 200 OK with an empty array:

`https://api.yelp.com/v3/businesses/istr-paris/reviews?locale=en_US`
```
{
    "reviews": [],
    "total": 2
}
```

(Changelog: https://www.yelp.com/developers/v3/changelog#changelog-20170705 )

Keeping this issue open to track the "give me reviews in any language" use case.

**Comment by vineus** [comment] 2017-07-07 20:47
@mittonk thank you!

_Sent from my Huawei Nexus 6P using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by watterso** [comment] 2017-11-30 00:57
Closed because of inactivity / Issue is resolved.

(To get reviews in different languages use the `locale` param, the default value is `en_US`)

**Comment by mittonk** [comment] 2017-11-30 14:26
Keeping this issue open to track the "give me reviews in any language" use case.

**Closed** 2017-11-30 14:27 UTC
Labels: enhancement, tracked-internally

**Comment by mittonk** [comment] 2017-11-30 14:30
@vineus : We've added a new `possible_languages` field that helps with this use case.

* https://www.yelp.com/developers/v3/changelog#changelog-20171004
* https://www.yelp.com/developers/documentation/v3/business_reviews

**Comment by ypicard** [comment] 2019-05-29 14:38
Is the `locale=*` option still in consideration ?
