### ISSUE TITLE
500 Internal Server Error returned when trying an introspection

### ISSUE THREAD

**Issue by PhilippeRiegert** [Yelp/yelp-fusion#251] opened 2017-06-16 19:56 UTC
I'm trying to use this GraphQL API in Swift, I'm currently using the [Apollo](https://github.com/apollographql/apollo-ios) library in my project,
and to make that library to work I need to download the `schema.json` as specified over there: [Apollo downloading chema](http://dev.apollodata.com/ios/downloading-schema.html).
For downloading this schema Apollo provide another library: [Apollo Codegen](https://github.com/apollographql/apollo-codegen) that will download the schema for you.

So I've created my token with the [authentication guide](https://www.yelp.com/developers/documentation/v3/authentication) and run this command line:

`$ apollo-codegen download-schema https://api.yelp.com/v3/graphql --output schema.json --header "Authorization: Bearer ###########"`

and it return me: 

`No introspection query result data found, server responded with: {"message":"The server has either erred or is incapable of performing the requested operation.\n\n\n\n\n","code":"500 Internal Server Error","title":"Internal Server Error"}`

So I've tried one more tool to download the schema to make sure that is not the tool the problem.
And with the library [graphql-js-schema-fetch](https://github.com/Shopify/graphql-js-schema-fetch) I'm receiving the same kind of error:

`"The server has either erred or is incapable of performing the requested operation.\n\n\n\n\n","code":"500 Internal Server Error","title":"Internal Server Error"`

Maybe I'm missing something, thanks for the help !

**Comment by tomelm** [comment] 2017-06-16 21:12
I'm not too sure about this to be honest, I'm not very familiar with the Apollo libraries. I tried a simple introspection query and GraphiQL is still working so I don't think introspection is broken completely. Let me see if I can find anything out.

**Comment by PhilippeRiegert** [comment] 2017-06-16 23:12
@tomelm Thanks so much for searching on it! Let me know if I could help on anything 😄

**Comment by stubailo** [comment] 2017-06-19 15:50
I've heard about similar issues of people using `fetch` to load data from the Yelp API - I'll look into it.

**Comment by PhilippeRiegert** [comment] 2017-07-18 01:24
Is anyone having any update on this issue ?
I've update my [apollo-codegen](https://github.com/apollographql/apollo-codegen) to `v0.15.2`,
and I'm still getting the same error message.
Thanks 😄 !

**Comment by conroywhitney** [comment] 2017-07-18 23:48
I'm getting the same error as well. While trying to load the schema using the [`graphql-client`](https://github.com/github/graphql-client#configuration) gem:

```
GraphQL::Client.load_schema(HTTP)
```

It was returning a cryptic response

```
KeyError: key not found: "data"
```

While searching for a solution to that issue, I found this thread and confirmed using Shopify's `graphql-js-schema-fetch` library which @PhilippeRiegert pointed out earlier:

```
graphql-js-schema-fetch https://api.yelp.com/v3/graphql --header "Authorization: Bearer XXXX"
```

Which returned the following response:

```
{"message":"The server has either erred or is incapable of performing the requested operation.\n\n\n\n\n","code":"500 Internal Server Error","title":"Internal Server Error"}
```

Let me know if I can provide any additional context. Thank you in advance for your help on this!

**Comment by conroywhitney** [comment] 2017-07-19 00:33
I was able to get around this initial problem of loading the schema by using Yelp's [GraphiQL interface](https://www.yelp.com/developers/graphiql) along with [the introspection query that the `graphql` gem uses under the hood](https://raw.githubusercontent.com/rmosolgo/graphql-ruby/master/lib/graphql/introspection/introspection_query.rb). So @tomelm is correct, it's not the introspection that's the issue, so it must have something to do with the library.

However, once I had finally constructed my query and sent it to Yelp, I got another 500 error:

```
#<GraphQL::Client::Errors @messages={"data"=>["500 Internal Server Error"]} @details={"data"=>[{"message"=>"500 Internal Server Error", "normalizedPath"=>["data"]}]}>
```

I'm pretty sure it's not my GraphQL query, because using `curl` gives back the expected results:

```
curl -X POST -H "Authorization: Bearer XXXX" https://api.yelp.com/v3/graphql --data '{ search(categories: "restaurants", limit: 5, location: "anchorage", term: "burritos") { business { id name photos url }}}'
```

Are you able to investigate the root cause of the 500 error? I could send my `ClientID` if that would help.

Thanks in advance!

**Comment by tomelm** [comment] 2017-07-19 01:23
Digging into a little bit, it looks like apollo-codegen is sending us a JSON request with the query inside of a query field. The API wasn't expecting any JSON, it's assuming that you're sending the GraphQL query raw in the body.

@conroywhitney I'm not sure about the Ruby gem but I'm guessing it's the same issue.

@stubailo do you know if clientlibs generally send the graphql queries in as JSON?

**Comment by pranayairan** [comment] 2017-07-19 02:23
I face the same issue as OP even for Android. I am not sure if this will be the right approach, but it can be simple if Yelp publishes the graphql.json (api schema) on github or a link in documentation. We can then use this schema file in native apps like Android or iOS with apollo.

**Comment by conroywhitney** [comment] 2017-07-19 19:13
@pranayairan -- I've created a gist with the results that I got by using [Yelp's GraphiQL interface](https://www.yelp.com/developers/graphiql) along with [the introspection query from the `graphql` ruby gem](https://raw.githubusercontent.com/rmosolgo/graphql-ruby/master/lib/graphql/introspection/introspection_query.rb). 

**This is not an official schema. I make no claims that it's correct or complete**, but it worked for me.

https://gist.github.com/conroywhitney/be62505ff16560f1dc26b770695c2cd4

**Comment by PhilippeRiegert** [comment] 2017-07-19 19:16
Thanks @conroywhitney for providing a temporary `Schema`!

**Comment by conroywhitney** [comment] 2017-07-19 19:18
@PhilippeRiegert -- it still doesn't fix our common issue of the `500` error, though :frowning_face:

**Comment by conroywhitney** [comment] 2017-07-19 19:32
@tomelm -- You are spot on. Here's the JSON request that's being sent by [`github/graphql-client`](https://github.com/github/graphql-client):

```
{
  "query": "query ContentProviders__Yelp__Query__SEARCH($categories: String!, $term: String!, $location: String!, $limit: Int!) {
    search(categories: $categories, term: $term, location: $location, limit: $limit) {
      business {
        id
        name
        photos
        url
      }
    }
  }",
  "variables": {
    "category": "restaurants",
    "limit": 5,
    "location": "anchorage",
    "term": "burritos"
  },
  "operationName": "ContentProviders__Yelp__Query__SEARCH"
}
```
This may seem like a dumb question, but how should I be sending variables to the Yelp Fusion GraphQL API if not in a separate hash? My understanding is that it is not a best practice to interpolate values directly; that for security reasons, the GraphQL endpoint should do that.

Thanks for all of your help in resolving this issue!

**Comment by pranayairan** [comment] 2017-07-19 21:46
thanks, @conroywhitney I will give it a try tonight.

**Comment by conroywhitney** [comment] 2017-07-20 05:38
For the time being, I've switched to using the regular Fusion API *without* `GraphQL`, but I would still love to figure out what the best course of action is w.r.t. `query`/`variables` for future reference.

Let me know if I can help with anything on my end. Thanks!

**Comment by tomelm** [comment] 2017-07-21 01:03
Hey everyone, I've got a fix in-flight but it'll be a few days before I can push it out. I have a few more kinks I need to iron out and it'll be set, I'll keep everyone posted on progress.

**Comment by pranayairan** [comment] 2017-07-22 20:25
@tomelm let us know if you need help in verifying the fix. I hooked up the schema that @conroywhitney provided and now able to reproduce the other 500 error with the normal query.

**Comment by tomelm** [comment] 2017-07-25 20:54
Hey everyone, I pushed out a fixed for this. I've double checked that apollo-codegen works now. This change also changed the default behavior for the API and expects JSON requests by default. Regular GraphQL requests still work if you pass in the content type header `Content-Type: application/graphql`.

I put up a small page here explaining: https://www.yelp.com/developers/graphql/guides/requests.

Closing this issue for now, let me know if anything else is still busted!

**Comment by pranayairan** [comment] 2017-07-25 22:50
awesome, I verified this on the Android app I am working on. Thanks @tomelm

**Comment by conroywhitney** [comment] 2017-07-25 23:45
I've verified that [`Shopify/graphql-js-schema-fetch`](https://github.com/Shopify/graphql-js-schema-fetch) and [`github/graphql-client`](https://github.com/github/graphql-client/) both work now.

@tomelm Thank you very much for such a quick and flexible fix. The new docs are perfect!

**Comment by PhilippeRiegert** [comment] 2017-07-26 20:33
Thanks @tomelm for this quick fix 🎉 
I'm now able to properly get the `schema` with [Apollo Codegen](https://github.com/apollographql/apollo-codegen) !

But when I'm trying a simple query in my iOS project with the [Apollo](https://github.com/apollographql/apollo-ios) framework:
```
{
    search(location:"Toronto") {
        total
        business {
            name
        }
    }
}
```
I'm getting this error:
```
Received error response (400 bad request): {
    "error": {
        "code": "CLIENT_ERROR", "description": "Bad Request"
    }
}
```

I pretty sure that this query is valid because it's working well in the [Yelp GraphiQL console](https://www.yelp.ca/developers/graphiql).

@pranayairan are you able to reproduce this error on your side on your Android project ?
Or am I the only one who having this issue 😞.

**Comment by pranayairan** [comment] 2017-07-26 21:27
@PhilippeRiegert this query works for me : 

`query SearchYelp($radius: Float!, $location: String!) {
  search(radius: $radius, location: $location, limit: 20, offset: 20) {
    total
    business {
      id
      name
      rating
      review_count
      photos
      price
      coordinates {
        latitude
        longitude
      }
      location {
        address1
        city
      }
      categories {
        title
      }
    }
  }
}`

Can you try this.

**Comment by PhilippeRiegert** [comment] 2017-07-26 22:21
@pranayairan Thanks so much for your help !
But I'm getting the same error with your query 😞

**Comment by pranayairan** [comment] 2017-07-26 23:08
interesting, what else do you pass? how are you setting the headers?

**Comment by tomelm** [comment] 2017-07-27 00:40
@PhilippeRiegert are you setting the right headers? You need to sent the content type header: `Content-Type: application/graphql`.

**Comment by PhilippeRiegert** [comment] 2017-07-27 02:58
@tomelm Apollo iOS is sending this POST request with the content type `application/json`

```
{
    "query": "query List2 {  search(location: \"toronto\") {    __typename    total    business {      __typename      name    }  }}",
    "variables": null
}
```
And I'm receving this error:
```
{
  "error": {
    "code": "CLIENT_ERROR",
    "description": "Bad Request"
  }
}
```
When I'm sending this same request with the content type `application/graphql
`
I'm receving this error:
```
<html>
 <head>
  <title>500 Internal Server Error</title>
 </head>
 <body>
  <h1>500 Internal Server Error</h1>
  The server has either erred or is incapable of performing the requested operation.<br/><br/>



 </body>
</html>
```
You can easily reproduce this error by trying the request on the [GraphiQL](https://github.com/skevy/graphiql-app) app for mac:

<img width="720" alt="yelp" src="https://user-images.githubusercontent.com/1270537/28652426-c8e537fa-7255-11e7-974b-9c5414679708.png">

Thanks for your help 🙏 .

**Comment by conroywhitney** [comment] 2017-07-27 16:57
Hey @PhilippeRiegert -- I just tried using the `GraphiQL` OSX app. Unfortunately it's hard to debug because it hides the error messages and/or uses its own more-vague errors; however, I was able to use cURL to see the root errors and figure out what was going wrong.

There are two things you can change to get your query to work:

1. To get rid of the `500 Internal Server Error`, add a custom header:

```
Header Name: Content-Type
Header Value: application/graphql
```

2. To get rid of the of the subsequent `Cannot query field "query" on type "Query"` error, change your query to:

```
{
  search(location: "toronto") {
    total
    business {
      name
    }
  }
}
```

The cURL line for all of this is:

`curl -X POST -H "Authorization: Bearer XXX" https://api.yelp.com/v3/graphql --data '{ search(location: "toronto") { total business { name }}}' -H "Content-Type: application/graphql"`

The bad news is that the GraphiQL OSX app still gets a vague error even with both of these changes and I'm not sure why:

```
SyntaxError: Unexpected token < in JSON at position 0
```

I'm inclined to think that's an issue with their app, though, and not the Yelp fusion GraphQL endpoint, since cURL works with the above changes.

Maybe try creating an issue on the [graphiql-app](https://github.com/skevy/graphiql-app) and seeing their thoughts?

**Comment by conroywhitney** [comment] 2017-07-27 17:11
I take it back 😁 

So, you can quite easily debug the GraphiQL app (since it's an Electron app) by opening up the chrome debugger (View => Toggle Developer Tools). In the `network` tab, you can see the request being generated. It turns out it's actually still sending a JSON format, so you don't need the custom header.

Going back to your original issue, here's what the GraphiQL OSX app is generating:

```
Request URL:https://api.yelp.com/v3/graphql
content-type:application/json
RequestPayload
{
	"query": "query { search(location: \"toronto\") { total business { name } } }",
	"variables": null,
	"operationName": null
}
```

And here's what the Yelp GraphiQL explorer is generating:

```
Request URL:https://www.yelp.com/developers/graphql_proxy
content-type:application/json
RequestPayload
{
	"query": "query { search(location: \"toronto\") { total business { name } } }",
	"variables": null
}
```

I can't figure it out, to be honest. But hopefully what I've found will be helpful to someone.

**Comment by PhilippeRiegert** [comment] 2017-07-27 17:15
@conroywhitney Thanks for your help 🙏 
The two requests sounds pretty similar, with some small differences, I hope that what you have debug could help @tomelm.

**Comment by tomelm** [comment] 2017-07-27 17:42
Thanks everyone, I'll take a look. Re-opening this for now until I get to the bottom of it.

**Comment by PhilippeRiegert** [comment] 2017-07-27 17:44
@tomelm Thanks !
At first I wasn't sure if I should open a new issue or continue on this one since the first issue `500 Internal Server Error returned when trying an introspection` is now fixed.

**Comment by tomelm** [comment] 2017-08-01 04:14
I think I've figured out what was causing the 500, looks like malformed requests were causing breaks. I'll push this out tomorrow and see if it helps.

**Comment by tomelm** [comment] 2017-08-02 00:33
I've pushed a fix to the 500, looks like that was happening on mismatching content types. Didn't have a chance to look into graphiql, will try again tomorrow.

**Comment by pranayairan** [comment] 2017-08-02 01:10
This is interesting, the Same API is working for me. @PhilippeRiegert in case you want to see it working on Android, here is the app I am working on consuming this API https://github.com/pranayairan/YelpQL. App is still WIP.

**Comment by PhilippeRiegert** [comment] 2017-08-02 01:49
@pranayairan Thanks a lot! I'll take a look at your project 👀 and try it on my side!
Just wondering are you able to make those search requests in [graphiql](https://github.com/skevy/graphiql-app)?

**Comment by pranayairan** [comment] 2017-08-02 03:20
@PhilippeRiegert yes I was able to get search request working check this file for network query that is using Apollo android  https://github.com/pranayairan/YelpQL/blob/master/app/src/main/java/binarybricks/com/yelpql/network/SearchAPI.java
this is the graphQL query that i am using https://github.com/pranayairan/YelpQL/blob/master/app/src/main/graphql/yelp/SearchQuery.graphql

**Comment by tomelm** [comment] 2017-08-03 00:45
Okay so as far as I can tell our GraphiQL console is fine. The GraphiQL app is including default header that it doesn't mention called `Accept-Language` and that's defaulting to `en-US`. Unfortunately, that's not a valid locale for our API, you can find those [here](https://www.yelp.com/developers/documentation/v3/supported_locales). To get the GraphiQL OSX app working, add a new header like this: `Accept-Language: en_US`. After that, everything started working for me.

I have a ticket internally to improve the error messaging for that particular 400 but I think everything else is working correctly.

**Comment by PhilippeRiegert** [comment] 2017-08-03 22:11
@tomelm Thanks so much for you help 🙏 
When I'm adding the header `Accept-Language: en_US` I'm getting ride of the `CLIENT_ERROR ` error.
But as you said it would be a good idea to improve the error message 😄 
Thanks again you all for your help !!!

**Comment by tomelm** [comment] 2017-08-03 23:39
Yep! We'll get that updated soon. Also trying to dig into why the other locales are failing, but that's a separate issue. I'm going to close this one out again

**Closed by tomelm** 2017-08-03 23:39 UTC
Labels: question, tracked-internally
