### ISSUE TITLE
Total number of search result is always 240

### ISSUE THREAD

**Issue by kySheryl** [Yelp/yelp-fusion#644] opened 2021-10-04 19:57 UTC
## Overview
- **Client ID:** _cO0NoGtFwnaDRR6Y51AEiw_
- **Issue type:** _question_
- **Summary:** _No matter what condition I put as the search query, the total number of business returned never exceed 240._
- **Platform:** _Desktop/web_

## Description
No matter what condition I put as the search query, the total number of business returned never exceeds 240. I have tried both business endpoint and GraphOL console. Could anyone help me with the issue?

### Endpoint
_Fusion Search API, GraphOL_

### Parameters or Sample Request
```
https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000
```

### Response
```
{
    "businesses": [
        {
            "id": "ykPKeM6upBQKN2VOAcSs_w",
            "alias": "the-giving-pies-san-jose",
            "name": "The Giving Pies",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/34KUP_6TfKFogNfpHL6y1A/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/the-giving-pies-san-jose?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 106,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "desserts",
                    "title": "Desserts"
                },
                {
                    "alias": "coffee",
                    "title": "Coffee & Tea"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 37.309478614245535,
                "longitude": -121.88707944005728
            },
            "transactions": [
                "delivery",
                "pickup"
            ],
            "price": "$$",
            "location": {
                "address1": "569 W Alma Ave",
                "address2": null,
                "address3": "",
                "city": "San Jose",
                "zip_code": "95125",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "569 W Alma Ave",
                    "San Jose, CA 95125"
                ]
            },
            "phone": "+14084750563",
            "display_phone": "(408) 475-0563",
            "distance": 3195.270478409326
        },
        {
            "id": "w5MeiyrvCT3icNL4FKpVMQ",
            "alias": "milk-bar-san-jose",
            "name": "Milk Bar",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/5KUZGX09PEcXvx6TfSK_fw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/milk-bar-san-jose?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 7,
            "categories": [
                {
                    "alias": "desserts",
                    "title": "Desserts"
                },
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                }
            ],
            "rating": 3.5,
            "coordinates": {
                "latitude": 37.251784930010935,
                "longitude": -121.86578932883799
            },
            "transactions": [],
            "price": "$$",
            "location": {
                "address1": "925 Blossom Hill Rd",
                "address2": "Ste 1705",
                "address3": "",
                "city": "San Jose",
                "zip_code": "95123",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "925 Blossom Hill Rd",
                    "Ste 1705",
                    "San Jose, CA 95123"
                ]
            },
            "phone": "+14086228414",
            "display_phone": "(408) 622-8414",
            "distance": 9780.062913550195
        },
        {
            "id": "lPkQK2N4g658SR_7BBxeaQ",
            "alias": "peters-bakery-san-jose-2",
            "name": "Peters' Bakery",
            "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/QDjFZWIqoF16igCnvUPwdw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/peters-bakery-san-jose-2?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 1853,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "donuts",
                    "title": "Donuts"
                },
                {
                    "alias": "cupcakes",
                    "title": "Cupcakes"
                }
            ],
            "rating": 4.5,
            "coordinates": {
                "latitude": 37.36573,
                "longitude": -121.82734
            },
            "transactions": [],
            "price": "$",
            "location": {
                "address1": "3108 Alum Rock Ave",
                "address2": "",
                "address3": "",
                "city": "San Jose",
                "zip_code": "95127",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "3108 Alum Rock Ave",
                    "San Jose, CA 95127"
                ]
            },
            "phone": "+14082583529",
            "display_phone": "(408) 258-3529",
            "distance": 6032.984612299355
        },
        {
            "id": "s5F7swyGwWvqL13MgPow3g",
            "alias": "43-and-company-milpitas",
            "name": "43 & Company",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/McPXoFkmv3ZQ76UA0MhkWA/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/43-and-company-milpitas?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 73,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "desserts",
                    "title": "Desserts"
                }
            ],
            "rating": 4.5,
            "coordinates": {
                "latitude": 37.410661,
                "longitude": -121.886323
            },
            "transactions": [
                "delivery",
                "pickup"
            ],
            "location": {
                "address1": "1558 Gladding Ct",
                "address2": null,
                "address3": null,
                "city": "Milpitas",
                "zip_code": "95035",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "1558 Gladding Ct",
                    "Milpitas, CA 95035"
                ]
            },
            "phone": "+14083180125",
            "display_phone": "(408) 318-0125",
            "distance": 8056.374861052186
        },
        {
            "id": "RHHUNpo6k4EhTdqp-qGLow",
            "alias": "greenlees-bakery-san-jose",
            "name": "Greenlee's Bakery",
            "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/MePnoNXGAE7D9JrwsypBpA/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/greenlees-bakery-san-jose?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 437,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 37.33198,
                "longitude": -121.91135
            },
            "transactions": [
                "delivery",
                "pickup"
            ],
            "price": "$$",
            "location": {
                "address1": "1081 The Alameda",
                "address2": "",
                "address3": "",
                "city": "San Jose",
                "zip_code": "95126",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "1081 The Alameda",
                    "San Jose, CA 95126"
                ]
            },
            "phone": "+14082874191",
            "display_phone": "(408) 287-4191",
            "distance": 2325.705287763636
        },
        {
            "id": "-Zeb6IBGQ70a_1stzuotFA",
            "alias": "sweetdragon-baking-company-san-jose",
            "name": "Sweetdragon Baking Company",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/j3V74lwSH8trIura32nDHg/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/sweetdragon-baking-company-san-jose?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 33,
            "categories": [
                {
                    "alias": "desserts",
                    "title": "Desserts"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 37.3144618,
                "longitude": -121.9053241
            },
            "transactions": [],
            "price": "$",
            "location": {
                "address1": "898 Lincoln Ave",
                "address2": "",
                "address3": "",
                "city": "San Jose",
                "zip_code": "95126",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "898 Lincoln Ave",
                    "San Jose, CA 95126"
                ]
            },
            "phone": "+14082057319",
            "display_phone": "(408) 205-7319",
            "distance": 3129.4103223988614
        },
        {
            "id": "UE_fY8Sc5P_l3kQ74j_ylw",
            "alias": "cezaine-pies-and-sweets-san-jose",
            "name": "Cezaine Pies and Sweets",
            "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/YuM3g0P-cKOLiYsk3wCw1w/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/cezaine-pies-and-sweets-san-jose?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 3,
            "categories": [
                {
                    "alias": "desserts",
                    "title": "Desserts"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 37.2701301574707,
                "longitude": -121.85092163085938
            },
            "transactions": [],
            "location": {
                "address1": "",
                "address2": null,
                "address3": "",
                "city": "San Jose",
                "zip_code": "95136",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "San Jose, CA 95136"
                ]
            },
            "phone": "+14088248892",
            "display_phone": "(408) 824-8892",
            "distance": 8298.221644874224
        },
        {
            "id": "B8Q9qOsBt8Q92YoSjibhiw",
            "alias": "marie-callenders-restaurant-and-bakery-san-jose",
            "name": "Marie Callenders Restaurant & Bakery",
            "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/z8zjU9ohL9ffUF0gdshQvw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/marie-callenders-restaurant-and-bakery-san-jose?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 303,
            "categories": [
                {
                    "alias": "tradamerican",
                    "title": "American (Traditional)"
                },
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                }
            ],
            "rating": 3.0,
            "coordinates": {
                "latitude": 37.25018,
                "longitude": -121.84311
            },
            "transactions": [
                "delivery"
            ],
            "price": "$$",
            "location": {
                "address1": "620 Blossom Hill Rd",
                "address2": "",
                "address3": "",
                "city": "San Jose",
                "zip_code": "95123",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "620 Blossom Hill Rd",
                    "San Jose, CA 95123"
                ]
            },
            "phone": "+14085780643",
            "display_phone": "(408) 578-0643",
            "distance": 10500.542621290197
        },
        {
            "id": "HYoVorD_bSN290pX6xgr9Q",
            "alias": "icing-on-the-cake-los-gatos",
            "name": "Icing on the Cake",
            "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/cl04gw6KNOVSjuix8yGxWA/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/icing-on-the-cake-los-gatos?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 1413,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "desserts",
                    "title": "Desserts"
                },
                {
                    "alias": "cupcakes",
                    "title": "Cupcakes"
                }
            ],
            "rating": 4.5,
            "coordinates": {
                "latitude": 37.2220766,
                "longitude": -121.9825641
            },
            "transactions": [
                "delivery"
            ],
            "price": "$$",
            "location": {
                "address1": "50 W Main St",
                "address2": "",
                "address3": "",
                "city": "Los Gatos",
                "zip_code": "95030",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "50 W Main St",
                    "Los Gatos, CA 95030"
                ]
            },
            "phone": "+14083542464",
            "display_phone": "(408) 354-2464",
            "distance": 15460.801812046631
        },
        {
            "id": "mGkAdhCnF19DsKuIa25qCA",
            "alias": "mcourse-santa-clara",
            "name": "MCourse",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/fJf20l26HvLMHg9TL2NtLw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/mcourse-santa-clara?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 60,
            "categories": [
                {
                    "alias": "cakeshop",
                    "title": "Patisserie/Cake Shop"
                },
                {
                    "alias": "customcakes",
                    "title": "Custom Cakes"
                },
                {
                    "alias": "desserts",
                    "title": "Desserts"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 37.35245,
                "longitude": -121.98738
            },
            "transactions": [],
            "location": {
                "address1": null,
                "address2": null,
                "address3": null,
                "city": "Santa Clara",
                "zip_code": "95051",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "Santa Clara, CA 95051"
                ]
            },
            "phone": "",
            "display_phone": "",
            "distance": 8743.924915727184
        },
        {
            "id": "fhExLvzQzluwYFwoSySJ6Q",
            "alias": "marie-callenders-sunnyvale-3",
            "name": "Marie Callender's",
            "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/pmVuLK0EVB8T5o1lOHSdWA/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/marie-callenders-sunnyvale-3?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 281,
            "categories": [
                {
                    "alias": "desserts",
                    "title": "Desserts"
                },
                {
                    "alias": "tradamerican",
                    "title": "American (Traditional)"
                },
                {
                    "alias": "breakfast_brunch",
                    "title": "Breakfast & Brunch"
                }
            ],
            "rating": 3.5,
            "coordinates": {
                "latitude": 37.358096695905,
                "longitude": -122.01981879335
            },
            "transactions": [
                "delivery"
            ],
            "price": "$$",
            "location": {
                "address1": "751 E El Camino Real",
                "address2": "",
                "address3": "",
                "city": "Sunnyvale",
                "zip_code": "94087",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "751 E El Camino Real",
                    "Sunnyvale, CA 94087"
                ]
            },
            "phone": "+14082453710",
            "display_phone": "(408) 245-3710",
            "distance": 12005.424624792046
        },
        {
            "id": "rTLv1Zlp64bK4BOe5SRjoA",
            "alias": "raoofs-san-jose-bean-pies-san-jose-2",
            "name": "Raoof's San Jose Bean Pies",
            "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/gC40rnvJEEcZP3OJzW3Esg/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/raoofs-san-jose-bean-pies-san-jose-2?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 47,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "foodstands",
                    "title": "Food Stands"
                },
                {
                    "alias": "desserts",
                    "title": "Desserts"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 37.35312,
                "longitude": -121.89457
            },
            "transactions": [],
            "price": "$$",
            "location": {
                "address1": "",
                "address2": "",
                "address3": "",
                "city": "San Jose",
                "zip_code": "95112",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "San Jose, CA 95112"
                ]
            },
            "phone": "+14085838129",
            "display_phone": "(408) 583-8129",
            "distance": 836.5950500149996
        },
        {
            "id": "1wKDQ7i_ybNFq_Zm5Cxavg",
            "alias": "sugar-butter-flour-sunnyvale",
            "name": "Sugar Butter Flour",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/oPalIX-KH0YyHB-EHFy6-A/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/sugar-butter-flour-sunnyvale?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 1322,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "desserts",
                    "title": "Desserts"
                },
                {
                    "alias": "customcakes",
                    "title": "Custom Cakes"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 37.3720663047332,
                "longitude": -122.057665586472
            },
            "transactions": [],
            "price": "$$",
            "location": {
                "address1": "669 S Bernardo Ave",
                "address2": null,
                "address3": "",
                "city": "Sunnyvale",
                "zip_code": "94087",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "669 S Bernardo Ave",
                    "Sunnyvale, CA 94087"
                ]
            },
            "phone": "+14087328597",
            "display_phone": "(408) 732-8597",
            "distance": 15605.026459976254
        },
        {
            "id": "EKhinIo4QXf4pJlhFebHrg",
            "alias": "babybearbaker-san-jose",
            "name": "BabyBearBaker",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/fhZaf7McHXSO2eHB_UVIXw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/babybearbaker-san-jose?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 16,
            "categories": [
                {
                    "alias": "desserts",
                    "title": "Desserts"
                }
            ],
            "rating": 5.0,
            "coordinates": {
                "latitude": 37.34699249267578,
                "longitude": -121.95552825927734
            },
            "transactions": [],
            "location": {
                "address1": null,
                "address2": null,
                "address3": null,
                "city": "San Jose",
                "zip_code": "95131",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "San Jose, CA 95131"
                ]
            },
            "phone": "+15106309307",
            "display_phone": "(510) 630-9307",
            "distance": 6148.52822538704
        },
        {
            "id": "O1T2g-EFgMMothckAIFYEQ",
            "alias": "la-patisserie-cupertino",
            "name": "La Patisserie",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/JKM9q3oJjcI2-sM3dst-Pw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/la-patisserie-cupertino?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 949,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "customcakes",
                    "title": "Custom Cakes"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 37.3218310882795,
                "longitude": -122.018986775533
            },
            "transactions": [
                "delivery"
            ],
            "price": "$$",
            "location": {
                "address1": "19758 Stevens Creek Blvd",
                "address2": "",
                "address3": "",
                "city": "Cupertino",
                "zip_code": "95014",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "19758 Stevens Creek Blvd",
                    "Cupertino, CA 95014"
                ]
            },
            "phone": "+14084464744",
            "display_phone": "(408) 446-4744",
            "distance": 11869.786966509713
        },
        {
            "id": "xWYmhBPCu-4B34fEUlEacg",
            "alias": "mamas-bakery-los-gatos-2",
            "name": "Mama's Bakery",
            "image_url": "https://s3-media3.fl.yelpcdn.com/bphoto/uiFjYOo5_taP-vqAPk4U5w/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/mamas-bakery-los-gatos-2?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 159,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                }
            ],
            "rating": 4.5,
            "coordinates": {
                "latitude": 37.23148,
                "longitude": -121.98009
            },
            "transactions": [],
            "price": "$",
            "location": {
                "address1": "473 N Santa Cruz Ave",
                "address2": "",
                "address3": "",
                "city": "Los Gatos",
                "zip_code": "95030",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "473 N Santa Cruz Ave",
                    "Los Gatos, CA 95030"
                ]
            },
            "phone": "+14088286262",
            "display_phone": "(408) 828-6262",
            "distance": 14480.687995276805
        },
        {
            "id": "-OnH7ai7mKxL8_ybqPMIBQ",
            "alias": "cest-si-bon-bakery-san-jose-2",
            "name": "C'est Si Bon Bakery",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/rn02asif5D-FjQ8k9cEWzQ/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/cest-si-bon-bakery-san-jose-2?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 721,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "desserts",
                    "title": "Desserts"
                },
                {
                    "alias": "customcakes",
                    "title": "Custom Cakes"
                }
            ],
            "rating": 4.5,
            "coordinates": {
                "latitude": 37.24478186656103,
                "longitude": -121.89047493558196
            },
            "transactions": [
                "delivery",
                "pickup"
            ],
            "price": "$$",
            "location": {
                "address1": "1375 Blossom Hill Rd",
                "address2": "Ste 38",
                "address3": "",
                "city": "San Jose",
                "zip_code": "95118",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "1375 Blossom Hill Rd",
                    "Ste 38",
                    "San Jose, CA 95118"
                ]
            },
            "phone": "+14082662253",
            "display_phone": "(408) 266-2253",
            "distance": 10394.996107530775
        },
        {
            "id": "H7hHQkC1YI6p67MKavSDAg",
            "alias": "sultan-bakery-san-jose",
            "name": "Sultan Bakery",
            "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/T1Lzk6GEmTLjatzVMe4hEQ/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/sultan-bakery-san-jose?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 367,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "falafel",
                    "title": "Falafel"
                },
                {
                    "alias": "desserts",
                    "title": "Desserts"
                }
            ],
            "rating": 4.5,
            "coordinates": {
                "latitude": 37.340341,
                "longitude": -121.912768
            },
            "transactions": [
                "delivery",
                "pickup"
            ],
            "price": "$",
            "location": {
                "address1": "670 Stockton Ave",
                "address2": null,
                "address3": "",
                "city": "San Jose",
                "zip_code": "95126",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "670 Stockton Ave",
                    "San Jose, CA 95126"
                ]
            },
            "phone": "+14082984008",
            "display_phone": "(408) 298-4008",
            "distance": 2349.4099889799913
        },
        {
            "id": "MPFAFExDFTLzs-ItB7pD6A",
            "alias": "pastelaria-adega-san-jose-2",
            "name": "Pastelaria Adega",
            "image_url": "https://s3-media1.fl.yelpcdn.com/bphoto/6upjFpKuR6T7T-D4zhpZEw/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/pastelaria-adega-san-jose-2?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 120,
            "categories": [
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "portuguese",
                    "title": "Portuguese"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 37.336243,
                "longitude": -121.889852
            },
            "transactions": [
                "delivery"
            ],
            "location": {
                "address1": "30 E Santa Clara St",
                "address2": "Ste 130",
                "address3": null,
                "city": "San Jose",
                "zip_code": "95113",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "30 E Santa Clara St",
                    "Ste 130",
                    "San Jose, CA 95113"
                ]
            },
            "phone": "+14083202936",
            "display_phone": "(408) 320-2936",
            "distance": 376.68099583827717
        },
        {
            "id": "u3lcIYyt5hhmK-gdBHxPrQ",
            "alias": "susiecakes-san-jose-2",
            "name": "SusieCakes",
            "image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/iMN7tVYrEcM4SgUx-Zs39w/o.jpg",
            "is_closed": false,
            "url": "https://www.yelp.com/biz/susiecakes-san-jose-2?adjust_creative=cO0NoGtFwnaDRR6Y51AEiw&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=cO0NoGtFwnaDRR6Y51AEiw",
            "review_count": 542,
            "categories": [
                {
                    "alias": "cupcakes",
                    "title": "Cupcakes"
                },
                {
                    "alias": "bakeries",
                    "title": "Bakeries"
                },
                {
                    "alias": "customcakes",
                    "title": "Custom Cakes"
                }
            ],
            "rating": 4.0,
            "coordinates": {
                "latitude": 37.3084897966721,
                "longitude": -121.901517435908
            },
            "transactions": [
                "delivery"
            ],
            "price": "$$",
            "location": {
                "address1": "1109 Lincoln Ave",
                "address2": "",
                "address3": "",
                "city": "San Jose",
                "zip_code": "95125",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "1109 Lincoln Ave",
                    "San Jose, CA 95125"
                ]
            },
            "phone": "+14084462253",
            "display_phone": "(408) 446-2253",
            "distance": 3567.0405588683384
        }
    ],
    "total": 240,
    "region": {
        "center": {
            "longitude": -121.88632860000001,
            "latitude": 37.3382082
        }
    }
}
```

**Comment by sue0914** [comment] 2021-10-10 06:05
I've been running into the same problem.

**Comment by gserapio** [comment] 2021-11-05 11:22
I'm seeing the same issue.

**Comment by raindata5** [comment] 2021-11-16 21:22
Have you tried using the limit clause?
I did and it printed out my desired quantity. 240 is the default and regarding the documentation it says 
_**Optional. Number of business results to return. By default, it will return 20. Maximum is 50.**_

**Comment by raindata5** [comment] 2021-11-16 21:35
Actually I notice this issue is happening to me in my python script. It's odd because when I use postman there's no problem.

**Comment by raindata5** [comment] 2021-11-16 23:14
Ok I can confirm it works. The offset doesn't seem to work when sent by the parameters argument in python. To be safe just send the parameters in the query string and that does it. 
BTW the json object returned always says 240 in the query string.

**Comment by instanttaylor** [comment] 2021-11-18 20:54
Same here. I used the sample Ruby code from this project and also tried the yelp/fusion rubygem and my own code and it always blows up after paginating to 240. Even if the offset starts close to that so it's not like we're getting 240 results, it just stops at 240. Tried a bunch of different locations but they all crash at 240.

**Comment by instanttaylor** [comment] 2021-12-01 18:38
This issue seems to be fixed for me as of 12/1/2021

**Comment by dd2676** [comment] 2021-12-01 18:48
Oh, that's good.

**Comment by rockdog** [comment] 2022-02-04 18:43
Thanks for reporting this issue @kySheryl.

I just verified that the **total** field is returning the expected number. Closing this issue.

**Closed by rockdog** 2022-02-04 18:43 UTC
