### ISSUE TITLE
How to access "More Info" establishment details

### ISSUE THREAD

**Issue by sidikinoel** [Yelp/yelp-fusion#63] opened 2016-09-26 05:10 UTC
Querying a restaurant through the YELP app on iphone returns a section called "More Info", which provides details on attributes such as: delivery, take out, outdoor seating, ambience, etc...
(See attached screenshot)

![fullsizerender 8](https://cloud.githubusercontent.com/assets/22439527/18840664/2bc15fb0-83c4-11e6-9823-720e5ee60bde.jpg)

However, when querying the v3 API for the same restaurant using the Business/{ID} endpoint, none of these attributes are available.  See query results below for the same restaurant.  

Is there a flag that needs to be added to the query to get these additional attributes?  

Thanks ahead.
sn. 

{
"url": "https://www.yelp.com/biz/molinari-delicatessen-san-francisco?adjust_creative=Vf7lAM6BvI6-STD6jD1giQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_lookup&utm_source=Vf7lAM6BvI6-STD6jD1giQ",
"categories":[
{
"title": "Delis",
"alias": "delis"
}
],
"name": "Molinari Delicatessen",
"image_url": "https://s3-media4.fl.yelpcdn.com/bphoto/H_vQ3ElMoQ8j1bKidrv_1w/o.jpg",
"price": "$$",
"hours":[
{
"is_open_now": false,
"open":[{"day": 0, "end": "1800", "is_overnight": false, "start": "0900"…],
"hours_type": "REGULAR"
}
],
"rating": 4.5,
"phone": "+14154212337",
"id": "molinari-delicatessen-san-francisco",
"photos":[
"https://s3-media3.fl.yelpcdn.com/bphoto/H_vQ3ElMoQ8j1bKidrv_1w/o.jpg",
"https://s3-media1.fl.yelpcdn.com/bphoto/H_P0rL_rcS_ogubBVw0AFg/o.jpg",
"https://s3-media3.fl.yelpcdn.com/bphoto/pLYs8eA_8iZIGaNlVrhjCw/o.jpg"
],
"coordinates":{
"longitude": -122.407821655273,
"latitude": 37.7983818054199
},
"review_count": 927,
"location":{
"zip_code": "94133",
"city": "San Francisco",
"address1": "373 Columbus Ave",
"country": "US",
"address3": "",
"address2": "",
"state": "CA"
}
}

**Comment by mittonk** [comment] 2016-09-26 13:59
@sidikinoel , some of these attributes aren't yet available in Yelp Fusion.  We're looking into it.

**Comment by sidikinoel** [comment] 2016-09-27 23:51
@mittonk Thanks for the quick response.  I really hope you consider adding these attributes in the Fusion API, along with more granular dietary qualifiers.  Also, I have updated the screenshot in my initial post.  I posted the wrong one.  Thanks ahead.

**Comment by kf6kjg** [comment] 2017-06-02 23:16
Looks like a duplicate of #62.

**Closed** 2023-12-18 14:01 UTC
Labels: enhancement
