### ISSUE TITLE
Yelp returns business id, name, phone, rating, price..., but not returning location related response?

### ISSUE THREAD

**Issue by yijiaow** [Yelp/yelp-fusion#274] opened 2017-08-03 19:44 UTC
Yelp! 

When I use AJAX to get response from Yelp Fusion API, I am **only getting business name, price, rating, phone**, etc but business.distance, businesses[x].location and businesses[x].coordinates.latitude keeps showing in console.log as “undefined”?
I followed instructions here: https://www.yelp.com/developers/documentation/v3/business_search1
For back-end, I followed the python sample code here https://github.com/Yelp/yelp-fusion/blob/master/fusion/python/sample.py

Not sure if it's a CORS issue because I send request thru a small Flask app and I did get other responses. Played around in console.log but location is always showing “object undefined”.

section of my success function in AJAX call:
`success: function(response) {`
						`self.places([]);`
						`response.forEach(function(business) {`
							`console.log('adding businesses...' + business.name);`
							`console.log('price: ' + business.price);`
							`console.log('rating: ' + business.rating);`
							`console.log('distance: ' + toString(business.distance));`
							`console.log('phone: ' + business.display_phone);`
							`console.log('location: ' + toString(business.location));`
							`console.log('lat: ' + toString(business.coordinates['latitude']));`
							`console.log('lng: ' + toString(business.coordinates.longitude)); }`

**Comment by tomelm** [comment] 2017-08-07 16:04
Is this happening on every business returned or only for some? Could you share the queries you're making where you're seeing empty values for location and coordinates?

**Comment by yijiaow** [comment] 2017-08-07 20:05
Yes it is happening on every business...(see below screen shot)
![image](https://user-images.githubusercontent.com/19718392/29043532-6af4eb76-7b70-11e7-932f-2ed11a59138d.png)

Python:
```
	url_params = {
			'term': request.args.get('term').replace(' ', '+'),
			'category_filter': 'food',
			'latitude': request.args.get('latitude'), 
			'longitude': request.args.get('longitude'),
			'radius': int(request.args.get('radius')),
			'sort_by': 'rating'
			}
	bearer_token = obtain_access_token(AUTH_PATH)
	headers = {'Authorization': 'Bearer %s' % bearer_token}
	response = requests.get(SEARCH_PATH, headers=headers, params=url_params)
	if response.status_code == 200:
		eprint('total: ' + str(response.json()['total']))
		return json.dumps(response.json()['businesses'])
	else:
		eprint("Received non-200 response({}) for business search, returning empty response".format(response.status_code))
```
Javascript:
```
			self.getCoords(geocoder, self.addressInput(), function(coords) {
				// This anonymous function will run when the callback is called.
				latitude = coords.lat();
				longitude = coords.lng();
				$.ajax({
					url: '/business_search',
					type: 'GET',
					data: {
						term: self.term(), 
						latitude: latitude,
						longitude: longitude, 
						radius: self.radius()},
					dataType: 'json',
					success: function(response) {
						self.places([]);
						response.forEach(function(business) {
							console.log('adding businesses...' + business.name);
							console.log('price: ' + business.price);
							console.log('rating: ' + business.rating);
							console.log('distance: ' + toString(business.distance));
							console.log('phone: ' + business.display_phone);
							console.log('location: ' + toString(business.location));
							console.log('lat: ' + toString(business.coordinates['latitude']));
							console.log('lng: ' + toString(business.coordinates.longitude));
							//self.places.push(new Place(business));
						});
```

**Comment by tomelm** [comment] 2017-08-07 20:27
Could you provide the actual query parameters you're sending to the API so that I can reproduce that here and debug?

**Comment by yijiaow** [comment] 2017-08-07 20:31
query parameters:
/business_search**?term=pie**&**latitude=37.3382082&longitude=-121.88632860000001**&**radius=17000**
this project's repo if you need it. 

https://github.com/yijiaow/udacity-map-project

**Comment by tomelm** [comment] 2017-08-07 20:44
@yijiaow I ran the same query you provided and it looks like I'm getting data. Could you try debugging the query with curl or a REST client?

URL: https://api.yelp.com/v3/businesses/search?term=pie&latitude=37.3382082&longitude=-121.88632860000001&radius=17000

With the exception of the first business, the response has coordinates, location, and distance:

Location:
```
[
	{
		"address1": "",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "",
		"country": "US",
		"state": "CA",
		"display_address": [
			"San Jose, CA"
		]
	},
	{
		"address1": "San Pedro Square",
		"address2": "Kaiser Hospital Santa Teresa",
		"address3": "",
		"city": "San Jose",
		"zip_code": "",
		"country": "US",
		"state": "CA",
		"display_address": [
			"San Pedro Square",
			"Kaiser Hospital Santa Teresa",
			"San Jose, CA"
		]
	},
	{
		"address1": "138 E Santa Clara St",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95113",
		"country": "US",
		"state": "CA",
		"display_address": [
			"138 E Santa Clara St",
			"San Jose, CA 95113"
		]
	},
	{
		"address1": "670 Stockton Ave",
		"address2": null,
		"address3": "",
		"city": "San Jose",
		"zip_code": "95126",
		"country": "US",
		"state": "CA",
		"display_address": [
			"670 Stockton Ave",
			"San Jose, CA 95126"
		]
	},
	{
		"address1": "3108 Alum Rock Ave",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95127",
		"country": "US",
		"state": "CA",
		"display_address": [
			"3108 Alum Rock Ave",
			"San Jose, CA 95127"
		]
	},
	{
		"address1": "896 Willow St",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95125",
		"country": "US",
		"state": "CA",
		"display_address": [
			"896 Willow St",
			"San Jose, CA 95125"
		]
	},
	{
		"address1": "1081 The Alameda",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95126",
		"country": "US",
		"state": "CA",
		"display_address": [
			"1081 The Alameda",
			"San Jose, CA 95126"
		]
	},
	{
		"address1": "1109 Lincoln Ave",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95125",
		"country": "US",
		"state": "CA",
		"display_address": [
			"1109 Lincoln Ave",
			"San Jose, CA 95125"
		]
	},
	{
		"address1": "",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95112",
		"country": "US",
		"state": "CA",
		"display_address": [
			"San Jose, CA 95112"
		]
	},
	{
		"address1": "898 Lincoln Ave",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95126",
		"country": "US",
		"state": "CA",
		"display_address": [
			"898 Lincoln Ave",
			"San Jose, CA 95126"
		]
	},
	{
		"address1": "754 The Alameda",
		"address2": "Ste 80",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95126",
		"country": "US",
		"state": "CA",
		"display_address": [
			"754 The Alameda",
			"Ste 80",
			"San Jose, CA 95126"
		]
	},
	{
		"address1": "192 W Saint John St",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95110",
		"country": "US",
		"state": "CA",
		"display_address": [
			"192 W Saint John St",
			"San Jose, CA 95110"
		]
	},
	{
		"address1": "59 Washington St",
		"address2": "Ste 242",
		"address3": "",
		"city": "Santa Clara",
		"zip_code": "95050",
		"country": "US",
		"state": "CA",
		"display_address": [
			"59 Washington St",
			"Ste 242",
			"Santa Clara, CA 95050"
		]
	},
	{
		"address1": "2905 Park Ave",
		"address2": "",
		"address3": "",
		"city": "Santa Clara",
		"zip_code": "95050",
		"country": "US",
		"state": "CA",
		"display_address": [
			"2905 Park Ave",
			"Santa Clara, CA 95050"
		]
	},
	{
		"address1": "989 Story Rd",
		"address2": "Ste 8039",
		"address3": "VietNam Town",
		"city": "San Jose",
		"zip_code": "95122",
		"country": "US",
		"state": "CA",
		"display_address": [
			"989 Story Rd",
			"Ste 8039",
			"VietNam Town",
			"San Jose, CA 95122"
		]
	},
	{
		"address1": "170 S Market St",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95113",
		"country": "US",
		"state": "CA",
		"display_address": [
			"170 S Market St",
			"San Jose, CA 95113"
		]
	},
	{
		"address1": "1920 Lafayette St",
		"address2": "Unit G",
		"address3": "",
		"city": "Santa Clara",
		"zip_code": "95050",
		"country": "US",
		"state": "CA",
		"display_address": [
			"1920 Lafayette St",
			"Unit G",
			"Santa Clara, CA 95050"
		]
	},
	{
		"address1": "1664 Coleman Ave",
		"address2": "",
		"address3": "",
		"city": "Santa Clara",
		"zip_code": "95050",
		"country": "US",
		"state": "CA",
		"display_address": [
			"1664 Coleman Ave",
			"Santa Clara, CA 95050"
		]
	},
	{
		"address1": "415 S King Rd",
		"address2": "",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95116",
		"country": "US",
		"state": "CA",
		"display_address": [
			"415 S King Rd",
			"San Jose, CA 95116"
		]
	},
	{
		"address1": "1305 N Bascom Ave",
		"address2": "Ste 1",
		"address3": "",
		"city": "San Jose",
		"zip_code": "95128",
		"country": "US",
		"state": "CA",
		"display_address": [
			"1305 N Bascom Ave",
			"Ste 1",
			"San Jose, CA 95128"
		]
	}
]
```

Coordinates
```
[
	{
		"latitude": null,
		"longitude": null
	},
	{
		"latitude": 37.3364966,
		"longitude": -121.8943123
	},
	{
		"latitude": 37.3372943,
		"longitude": -121.8875862
	},
	{
		"latitude": 37.340341,
		"longitude": -121.912768
	},
	{
		"latitude": 37.36573,
		"longitude": -121.82734
	},
	{
		"latitude": 37.3101399,
		"longitude": -121.89698
	},
	{
		"latitude": 37.33198,
		"longitude": -121.91135
	},
	{
		"latitude": 37.3084897966721,
		"longitude": -121.901517435908
	},
	{
		"latitude": 37.33165,
		"longitude": -121.87878
	},
	{
		"latitude": 37.3144697,
		"longitude": -121.905311
	},
	{
		"latitude": 37.331594567997,
		"longitude": -121.905520934925
	},
	{
		"latitude": 37.3364298368866,
		"longitude": -121.894975429993
	},
	{
		"latitude": 37.3392792,
		"longitude": -121.9382172
	},
	{
		"latitude": 37.3456058,
		"longitude": -121.9375109
	},
	{
		"latitude": 37.3326526593,
		"longitude": -121.858024419
	},
	{
		"latitude": 37.332462660521,
		"longitude": -121.888761061584
	},
	{
		"latitude": 37.3590507507324,
		"longitude": -121.948722839355
	},
	{
		"latitude": 37.3589414,
		"longitude": -121.9392165
	},
	{
		"latitude": 37.3451,
		"longitude": -121.84873
	},
	{
		"latitude": 37.33751,
		"longitude": -121.9383
	}
]
```

Distance:
```
[
	537.7921178224,
	730.6746872222,
	150.5439239326,
	2349.093730552,
	6033.955271702,
	3259.6798677079996,
	2322.944369562,
	3566.8864584399994,
	836.785506238,
	3128.059191138,
	1848.850347368,
	789.3626660296,
	4600.248500459999,
	4598.448936471999,
	2577.5570853579998,
	674.0722199339999,
	5969.221018608,
	5196.589759328,
	3423.6656591499996,
	4594.692575978
]
```

**Comment by mittonk** [comment] 2017-08-08 16:00
Looking at this a different way:
Not every business returned by the Fusion API will include latitude & longitude.  For some businesses, we know only vaguely where they are --- enough to include in search results, but not enough to list a specific storefront location.

The first business result is exactly that case:
```
{
    "businesses": [
        {
            "id": "the-perfect-crust-san-jose",
            "name": "The Perfect Crust",
            "coordinates": {
                "latitude": null,
                "longitude": null
            },
            "location": {
                "address1": "",
                "address2": "",
                "address3": "",
                "city": "San Jose",
                "zip_code": "",
                "country": "US",
                "state": "CA",
                "display_address": [
                    "San Jose, CA"
                ]
            },
...
```

Note `coordinates.latitude` and `coordinates.longitude` are both `null`, and `distance` is not provided.

Your code will need to be able to handle this case.

**Comment by yijiaow** [comment] 2017-08-08 16:07
You are right, I will work on handling the null cases separately. (Question mark is great idea).
Also, I figured out the issue is actually in my Javascript code. More specifically it has something to do with looping (response shows most businesses location/latlng). what exactly i don't know yet, still working on it...

**Comment by tomelm** [comment] 2017-08-08 17:17
@yijiaow cool, glad to hear you're making progress. I'm going to close this issue as it looks like it's not API related.

**Closed by tomelm** 2017-08-08 17:17 UTC
Labels: question
