### ISSUE TITLE
Add hours to /businesses/search endpoint

### ISSUE THREAD

**Issue by grtkachenko** [Yelp/yelp-fusion#9] opened 2016-07-19 09:31 UTC
I see that **hours** is available in the /businesses/{id} endpoint only (not in /businesses/search). It would be nice to have this field (or at least shorten version of it) in /businesses/search so that we can do only **one** call instead of **N** (where N is desired number of places from response) to get the hours of businesses.

**Comment by mittonk** [comment] 2016-07-19 15:07
@tomelm : We've had a variety of conversations about this "one big response vs several small ones".  Sounds worth clarifying the plan.

**Comment by tomelm** [comment] 2016-07-19 17:00
@grtkachenko could you describe the use case you'd like to build? We need to weight the pros/cons of adding the data to the endpoint

**Comment by davecom** [comment] 2016-07-19 18:01
I would like this too - any app that does a search of the Yelp API with the purposes of directing a user to a business will likely want to know whether the business is currently closed/when it will close. If we want to list all businesses that meet a certain criteria and include in that listing hours, it would require N+1 API calls, where N is the number of businesses.

**Comment by watterso** [comment] 2016-07-19 18:17
If your use case for hours in search responses is to search for only open businesses, you should use the `open_now_filter` param described in the [/business/search docs](https://github.com/Yelp/yelp-api-v3/blob/master/docs/api-references/businesses-search.md).

If you have another use case for having hours in search results, we are all ears!

**Comment by arun4444** [comment] 2016-07-19 18:25
We are also working on an app which relies on business hours to direct people to those that are open. The use-case is to plan trips to various businesses in the future. Right now, this would involve making separate calls for each business returned by the search endpoint. Perhaps a filter that returns hours for businesses when requested would be great for us.

**Comment by tomelm** [comment] 2016-07-19 18:28
@arun4444 would a search parameter that specifies the open time be helpful instead of open now? Even with hours, what you're describing would involve you parsing all the times and seeing if it's open at the specific time so returning the business hours may not be the easiest approach.

**Comment by arun4444** [comment] 2016-07-19 18:41
This would work if we were returning individual businesses.  We are coordinating an itinerary among various destinations and scheduling them based on open hours.  The full info for the open hours window allows us to form a schedule based on multiple destinations.

**Comment by davecom** [comment] 2016-07-19 19:12
Use case would be to not only show whether a business is open now but also when it is closing in search results.

**Comment by mars271** [comment] 2016-07-19 19:52
The main use case for us is to show current business hours in search results.  By having hours added to the response, we could have logic in our apps to parse hours and show something like "Open until 11:00PM" for each result.

**Comment by grtkachenko** [comment] 2016-07-20 08:28
@tomelm We are working on the app where we show nearby businesses and their short description, which includes working hours for a few days (or even 1 week). So for user it's generally not about "open right now or not", but about "would it be open tomorrow at 10am"

**Comment by sp00m** [comment] 2016-07-20 16:12
Same here: instead of displaying only open businesses thanks to the `open_now_filter` param, I believe it would be more user-friendly show all businesses, but with either "Closing at XX:XX" or "Opening at XX:XX", depending on whether business is currently open or not. So :+1: for having (the possibility to get) hours directly in search responses :)

**Comment by k06a** [comment] 2016-07-21 20:11
:+1:

**Comment by tomelm** [comment] 2016-08-08 16:39
Circling back here, we're looking into doing this. There are some technical concerns on the backend we're hoping to figure out first, I'll keep you all posted!

**Comment by callmenicholi** [comment] 2016-08-12 00:28
I represent a restaurant. One of the challenges is that the kitchen closes at 9 pm while the bar stays open until 11:30 pm. The problem is that customers don't always verify. We got hit with a negative review on Yelp. Two sets of hours is something to consider.

**Comment by taylorbond** [comment] 2017-04-02 19:28
Hey all - writing to see if this is still planned to be implemented. It would be really nice to not have to do N+1 calls to get hours.

**Comment by sp00m** [comment] 2017-04-03 09:00
Totally agree, haven't migrated to V3 yet as I'm waiting for this feature to be implemented.

**Comment by tomelm** [comment] 2017-05-05 17:50
Hey everyone! We released a GraphQL API that lets you do this: https://www.yelp.com/developers/graphql/query/search (find: Search with business hours)

**Comment by davecom** [comment] 2017-05-05 18:22
It would still be nice to have this in the main API, so that one is not having to do both regular API calls plus GraphQL calls in the same app.

**Comment by tomelm** [comment] 2017-05-05 20:53
@davecom both use the same auth so there isn't any additional setup necessary. Is there a big feature in the regular API that graphql is missing that you want?

**Comment by davecom** [comment] 2017-05-06 05:34
It's the other way around - don't want to have to use GraphQL. Why not deliver feature parity to both APIs?

**Comment by knaaptime** [comment] 2017-10-05 22:32
is there still any potential this could be added? I'm doing academic research on neighborhood change and looking at whether businesses change their hours of operation as a function of evolving spatial characteristics

**Comment by dan98765** [comment] 2018-12-21 18:40
Update: adding this feature is still not planned due to concerns about adding latency to the Business Search endpoint for everyone, even those who do not want the hours data. Our current best guidance is still to either A) make multiple calls to the business lookup (/v3/businesses/{id}) endpoint or to use the beta GraphQL API.

**Closed** 2023-12-18 14:00 UTC
Labels: enhancement
