### ISSUE TITLE
Authentication error.

### ISSUE THREAD

**Issue by YusufDerie** [Yelp/yelp-fusion#281] opened 2017-08-15 00:50 UTC
## Overview
- **Client ID:**:  JXHq4-NX93D1H1cp3rX80w
- **Issue type:**: Post requests
- **Summary:**:  requests don't work with Yelp API due to a restriction with CORS? How does that affect me?
- **Platform:** : web

## Description
 I'm trying to use HTML and CSS for my website. and Javascript to deal handle the API and pull random restaurant data

so reading through some threads posted like #253  and #64 am I unable to go through with this project? I'm fairly new to dealing with APIs and kinda lost right now. Seems like the issue's with requests are stopping me I think. Any tips or clarification is appreciated thanks!

var data = "client_id=JXHq4-NX93D1H1cp3rX80w&client_secret="PASTE SECRET HERE";

var xhr = new XMLHttpRequest();
xhr.withCredentials = true;

xhr.addEventListener("readystatechange", function () {
  if (this.readyState === 4) {
    console.log(this.responseText);
  }
});

xhr.open("POST", "https://api.yelp.com/oauth2/token");
xhr.setRequestHeader("content-type", "application/x-www-form-urlencoded");
xhr.setRequestHeader("cache-control", "no-cache");
xhr.setRequestHeader("postman-token", "ce087809-66e7-0115-fb64-e38eba0346ea");

xhr.send(data);

<img width="552" alt="screen shot 2017-08-14 at 7 42 21 pm" src="https://user-images.githubusercontent.com/24668498/29297758-c0fb87ba-8128-11e7-90fb-b17e1de9322f.png">

**Comment by tomelm** [comment] 2017-08-15 20:51
Hey @YusufDerie, looks like you're trying to make a CORS request which is not supported by the API. We don't have a timeline at the moment on when we'd make available.

**Comment by mittonk** [comment] 2017-08-17 12:29
(And the workaround is for you to build a very small back-end application for your Yelp functionality; there's more details in #44 and #64.)

**Comment by watterso** [comment] 2017-11-30 01:00
Closing as a dupe of #64

**Closed by watterso** 2017-11-30 01:00 UTC
Labels: enhancement, tracked-internally
