### ISSUE TITLE
VALIDATION_ERROR -> BUSINESS_UNAVAILABLE

### ISSUE THREAD

**Issue by bizmate** [Yelp/yelp-fusion#66] opened 2016-09-28 20:55 UTC
When calling a business i can get its details but calling the reviews returns an error. In detail
1. calling the business endpoint `https://api.yelp.com/v3/businesses/clínica-alexandre-herculano-lisboa-2` I get the correct response with the business details and everything i was expecting.
2. calling the business endpoint with **reviews** `https://api.yelp.com/v3/businesses/clínica-alexandre-herculano-lisboa-2/reviews`
   responds with 

```
{
  "error": {
    "code": "VALIDATION_ERROR",
    "description": "{'error': {'code': 'BUSINESS_UNAVAILABLE', 'description': 'We may not be able to provide details for certain businesses, for example if they do not have any reviews yet.'}}"
  }
}
```

Could you please confirm the meaning of this response? The business has reviews and I think it has been claimed. Anything else that could cause this response?

**Comment by mittonk** [comment] 2016-09-28 21:55
Reproduced issue.

In English on https://www.yelp.com/biz/cl%C3%ADnica-alexandre-herculano-lisboa-2, I see one review by "Jeroen M." but "Language: English (0)".  Something's definitely out-of-sync on the back end.

(On the Portuguese side:
https://www.yelp.pt/biz/cl%C3%ADnica-alexandre-herculano-lisboa-2 shows 2 reviews in Portuguese, and https://api.yelp.com/v3/businesses/clínica-alexandre-herculano-lisboa-2/reviews?locale=pt_PT retrieves them as expected.)

**Comment by bizmate** [comment] 2016-09-28 22:11
@mittonk thanks for the quick response. I cannot see anything in the other api responses to work out the right locale (apart from country in address that is not complete with language). I assume from what you said above anyway is that this is a bug in the platform and the locale should not be required?

**Comment by mittonk** [comment] 2016-09-28 22:33
Locale defaults to en_US if not specified.  If you want English reviews, that's a fine default.

This back-end bug seems to be affecting this one review, which happens to be in English.  Locale is definitely not required.

**Comment by bizmate** [comment] 2016-09-30 05:31
I would not restrict/filter an api resource by default as it would make it very complex to handle locales and it is not the experience on the actual site (i.e. all reviews are shown regardless of clients locales). I would definitely prefer if I could fetch all with no language limitations as a default and apply a locale if my use case requires one. If a default is applied at the moment it would be great to override it with a fetch all like locale=* or something.

**Comment by mittonk** [comment] 2016-09-30 20:45
OK, locale=* is certainly an enhancement to consider for the future.

For the original business: Now that that odd review is straightened out, business shows 0 English reviews, which means it's not returnable by the API.  Not a simple or straightforward situation, but working as designed.

**Comment by bizmate** [comment] 2016-09-30 21:35
Could you please clarify what this means for API clients? i.e. what is the designed experience? In a restful service limiting resources by default is not really a good practice btw, hence the use of filters. But also if a filter is applied by default a client needs to be able to identify how to call the resource in this case as otherwise it is not predictable. 

In short, if we really need a locale then something on the business end point needs to tell what the available locales are and ideally how many reviews are available per locale. This is not a 1 to 1 country to locale relationship as this is not always a match for countries with multiple languages (i.e. switzerland) or viceversa languages used in several countries like all the en_ possibilities.

It really is complicated if a locale is required. I hope the above is reasonable

**Comment by mittonk** [comment] 2016-10-03 20:14
Most apps and websites I use show one language at a time, usually with a way of choosing.

www.yelp.com works that way, with a language picker in the lower-right corner of the page.

The Yelp iOS and Android apps read the user's locale from the operating system, and show content in that language or a close match.

locale=* is indeed an interesting enhancement, but I wouldn't expect it to be a standard mode for most apps.  Does it makes sense to show Japanese and English reviews to a user who speaks French?

**Comment by mittonk** [comment] 2016-10-03 20:14
@guangyang , @tomelm : Interesting use case we should consider for the future here --- out of our usual locale model.

**Comment by mittonk** [comment] 2016-10-04 19:04
(Backend's out of sync and showing the problematic review on WWW again, so that's back in the confusion.)

**Comment by mittonk** [comment] 2016-12-09 17:37
#136  better captures the `locale=*` or `lang_filter=false` use case; marking this older ticket as a duplicate of that simpler one, see that for updates.

**Closed by mittonk** 2016-12-09 17:37 UTC
Labels: enhancement, tracked-internally

**Comment by mittonk** [comment] 2017-01-11 17:59
(Note: 
>  the experience on the actual site (i.e. all reviews are shown regardless of clients locales)
is not entirely accurate, www.yelp.com usually shows only reviews in the language selected in the bottom-right language picker.)
